### ISSUE TITLE
Add more search syntax, examples

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/adsabs.github.io#11]
Need to cover:
- disabling synonyms via the famous "="
- the bibgroup field
- review of the property:OPENACCESS variations
- add documentation for doctype field

**Comment by jonnybazookatone** [comment]
If you fill out some of this content (tersely is fine for now), I can put it in and try to get the ticket closed.

**Comment by aaccomazzi** [comment]
Hopefully semi-complete docs by now via 2b71017469164a51421ec2499bd9985f413a382d
