### ISSUE TITLE
External links to old help docs

### ISSUE THREAD

**Issue by jonnybazookatone** [adsabs/adsabs.github.io#12]
There is a link to what bibstems are in search-syntax. This should be replaced with docs within the repo, rather than pointing to classic-related documentation.

**Comment by aaccomazzi** [comment]
The link takes to the page http://adsabs.harvard.edu/abs_doc/journal_abbr.html, which could be replicated in our help pages but the links contained in there are generated via ADS classic content, so those cannot be ported at this point.  Is it worth rewriting the intermediate page at this point?  I think not.
