### ISSUE TITLE
rss atom blog feed

### ISSUE THREAD

**Issue by migueldvb** [adsabs/adsabs.github.io#33]
Is there an rss or atom feed for the ADS blog?

**Comment by jonnybazookatone** [comment]
Hi Miguel, not yet. But it won't be too difficult to add, so maybe later next week. The issue will be closed when it's available.

**Comment by migueldvb** [comment]
@jonnybazookatone thank you for the information.

**Comment by jonnybazookatone** [comment]
OK, there is a basic one implemented now: http://adsabs.github.io/feed.xml

**Comment by migueldvb** [comment]
That is fantastic, thank you! Is there any reason why the full articles are not included in the feed? I would think that is more useful. The content of the final article in the feed ends in the middle of an hyperlink tag and that would break my simple feed parser.

```
For many scientists, it&#8217;s all about the numbers and when it comes to e
valuating each other, it&#8217;s no different. Project managers and administrat
ors also want to be able to evaluate the impact of programs or instruments. As 
a result, <a...
```

**Comment by jonnybazookatone** [comment]
No reason, it was just pretty bloated, didn't think of people manually parsing and breaking - sorry. I added the full content, you shouldn't have any issues now.

**Comment by jonnybazookatone** [comment]
FYI, it will just show the last 10 posts - even though we haven't reached double digits yet ;-).

**Comment by migueldvb** [comment]
That is great, thank you for the quick answer!
