### ISSUE TITLE
number of articles per page

### ISSUE THREAD

**Issue by migueldvb** [adsabs/adsabs.github.io#37]
The number of articles per page resets itself to 20 after a new search. It would be useful to allow the default number of articles displayed in searches be defined in the user settings or to remember the user preference.

**Comment by jonnybazookatone** [comment]
@aholachek @aaccomazzi

**Comment by jonnybazookatone** [comment]
You can define the number of articles per page to be displayed at the bottom of a page. This value is then used for all lists throughout the ADS services (bar the libraries at the moment).

We don't plan on adding a specific section in the user settings area at the moment, but we will retain the number you use throughout your sessions.

Do note, if you use a different machine (or a private/incognito window), it will not know your pagination choice that you set before.
