### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by ehenneken** [adsabs/adsabs.github.io#61]
In the search part of the Help, there is a link

  http://adsabs.github.io/help/actions/filter

which currently results in a 404.

**Comment by jonnybazookatone** [comment]
Can you give more information?

I can see there is a dead link on this page: http://adsabs.github.io/help/actions/analyze

with `view it in the [results graph visualization]({{ site.baseurl }}/actions/visualize#results-graph)`

and there is another dead link inside: http://adsabs.github.io/help/actions/visualize:

`The default graph shows the [recent views]({{site.baseurl}}/actions/analyze#recent-views)`

@aholachek: I guess these are remnants from some changes you made to these pages?

**Comment by ehenneken** [comment]
It is the link "“Filter your search” section" on http://adsabs.github.io/help/search/search-syntax

**Comment by jonnybazookatone** [comment]
ah yes;

`["Filter your search" section]({{ site.baseurl }}/help/actions/filter).` in `help/search/_posts/2015-02-09-search-syntax.md`
