### ISSUE TITLE
Add TOC to the Help Pages Landing Page

### ISSUE THREAD

**Issue by vsudilov** [adsabs/adsabs.github.io#8]
_From @kelle on June 15, 2015 20:2_

I think the current Help Pages landing page: http://adsabs.github.io/help/ 
should include the Table of Contents. Just a repeat of the info in the left sidebar. And remove the "Under Construction" text....all help pages are always under construction! :) 

_Copied from original issue: adsabs/bumblebee#418_

**Comment by jonnybazookatone** [comment]
I'm inclined to leave it the way it is without duplicating the content. Especially as it would encourage people to use the side bar to navigate when on other pages, I don't see the need for a TOC on the centre of the landing page.

Any other strong feelings?

**Comment by aholachek** [comment]
I agree

**Comment by jonnybazookatone** [comment]
I'll close it then unless someone re-opens it with strong feelings.

**Comment by kelle** [comment]
I cant quite put my finger on it, but something is just a little "off" about this page. Maybe the words could be improved a bit more. Right now you have 1) This is what's here (kinda), 2) You can find this other thing at this other place 3) to search what's here, go to the upper right. 

The first sentence says: "This site is a place to find documentation, tutorials, and information about new features."
- Are there any tutorials? I don't see any. If there are some, tell folks how to get there.
- Info about new features? It looks like this site just has documentation and the info about new features is in a different place (according to the next sentence: "To view the latest information about the ADS, visit the ADS blog.")

Try this:
This site contains the documentation for ADS Services . The topics are listed in the left sidebar. The search bar in the upper right can be used to search the entire site.

To view the latest information about the ADS, visit the ADS blog.

If you can't find what you're looking for, please reach out to <email> or Tweet us at @adsabs.

**Comment by jonnybazookatone** [comment]
How about:

```
This site is a place to find documentation, tutorials, and other general information about the ADS services. The topics are listed in the left sidebar and the search bar in the upper right can be used to search the entire site.

To view the latest information about the ADS, visit the ADS blog.

If you cannot find what you are looking for, please reach out adshelp@cfa.harvard.edu or tweet us at @adsabs.
```

I'd go as far to say that some of the help pages are more tutorial like, and some other parts, such as disclaimer details/logos, are just documentation, and so I'd leave the start of the first sentence as is.

**Comment by kelle** [comment]
sounds good!

**Comment by jonnybazookatone** [comment]
Done. Thanks for the suggestions, keep them coming - we'll make sure the tickets don't go stale.
